### ISSUE TITLE
OIDC Authorization code flow

### ISSUE THREAD

**Issue by johnmarcou** [GetLevvel/oauth2-oidc-debugger#1]
Hi,

I am using your debugger with Keycloak, but I had to add the OIDC Authorization code flow here to auto-populate the "Authorization Code" textbox.

```
  if (  (agt == "oidc_authorization_code_flow" ||
         agt == "authorization_grant" ||
         agt == "oidc_hybrid_code_id_token" ||
         agt == "oidc_hybrid_code_token" ||
         agt == "oidc_hybrid_code_id_token_token" ) &&
        pathname == "/callback")
```

I am not as OIDC expert and not sure at all about that, but at least, it works :)

https://github.com/GetLevvel/oauth2-oidc-debugger/blob/4028707aca560af7a521f02ee6b497be83370a00/client/public/js/forms.js#L612

Thanks for this tool.

**Comment by klaforce** [comment]
@johnmarcou thank you for your submission. This project has been moved to https://github.com/rcbj/oauth2-oidc-debugger. Would you mind resubmitting the issue there? Thank you.
